// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Vute Tech LTD
// Copyright (C) 2026 Bor contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v7.34.1
// source: ui.proto

package borui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldUi carries display metadata for policy editor UI generation.
// Attach it to any field in a *Policy message via (bor.ui.field).
// The protoc-gen-bor-ui plugin reads these options and generates
// *_ui.ts files consumed by PolicyDetailsModal.tsx.
type FieldUi struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group is the section name shown in the tree-view editor (required on
	// top-level *Policy fields; omitted on sub-message fields).
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// label is the human-readable field name shown in the UI.
	// If empty the generator derives a label from the proto field name by
	// splitting on camelCase/PascalCase word boundaries.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// description overrides the proto field's leading comment as the
	// tooltip/helper text.  Usually omitted — the field comment is used.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// chrome_only marks policies that depend on Google cloud services and
	// are no-ops in open-source Chromium builds.  Has no effect on other
	// policy message types.
	ChromeOnly bool `protobuf:"varint,4,opt,name=chrome_only,json=chromeOnly,proto3" json:"chrome_only,omitempty"`
	// int_options lists allowed integer values for integer-enum fields.
	// When set, the generator emits type "integer-enum" and an intOptions
	// array.  Mutually exclusive with string_options.
	IntOptions []*IntOption `protobuf:"bytes,5,rep,name=int_options,json=intOptions,proto3" json:"int_options,omitempty"`
	// string_options lists allowed string values for string-enum/select
	// fields.  When set, the generator emits type "string-enum".
	// Mutually exclusive with int_options.
	StringOptions []string `protobuf:"bytes,6,rep,name=string_options,json=stringOptions,proto3" json:"string_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldUi) Reset() {
	*x = FieldUi{}
	mi := &file_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldUi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldUi) ProtoMessage() {}

func (x *FieldUi) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldUi.ProtoReflect.Descriptor instead.
func (*FieldUi) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{0}
}

func (x *FieldUi) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FieldUi) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FieldUi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldUi) GetChromeOnly() bool {
	if x != nil {
		return x.ChromeOnly
	}
	return false
}

func (x *FieldUi) GetIntOptions() []*IntOption {
	if x != nil {
		return x.IntOptions
	}
	return nil
}

func (x *FieldUi) GetStringOptions() []string {
	if x != nil {
		return x.StringOptions
	}
	return nil
}

// IntOption is one allowed value for an integer-enum policy field.
type IntOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntOption) Reset() {
	*x = IntOption{}
	mi := &file_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntOption) ProtoMessage() {}

func (x *IntOption) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntOption.ProtoReflect.Descriptor instead.
func (*IntOption) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{1}
}

func (x *IntOption) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IntOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var file_ui_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldUi)(nil),
		Field:         50000,
		Name:          "bor.ui.field",
		Tag:           "bytes,50000,opt,name=field",
		Filename:      "ui.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// field carries UI display metadata for the protoc-gen-bor-ui generator.
	//
	// optional bor.ui.FieldUi field = 50000;
	E_Field = &file_ui_proto_extTypes[0]
)

var File_ui_proto protoreflect.FileDescriptor

var file_ui_proto_rawDesc = []byte{
	0x0a, 0x08, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x6f, 0x72, 0x2e,
	0x75, 0x69, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x01, 0x0a, 0x07, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x55, 0x69,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x12,
	0x32, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x75, 0x69, 0x2e, 0x49, 0x6e,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x37, 0x0a, 0x09, 0x49, 0x6e,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x3a, 0x46, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x75, 0x69, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x55, 0x69, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x75, 0x74, 0x65, 0x54, 0x65,
	0x63, 0x68, 0x2f, 0x42, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x6f, 0x72, 0x75, 0x69, 0x3b, 0x62, 0x6f, 0x72,
	0x75, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ui_proto_rawDescOnce sync.Once
	file_ui_proto_rawDescData = file_ui_proto_rawDesc
)

func file_ui_proto_rawDescGZIP() []byte {
	file_ui_proto_rawDescOnce.Do(func() {
		file_ui_proto_rawDescData = protoimpl.X.CompressGZIP(file_ui_proto_rawDescData)
	})
	return file_ui_proto_rawDescData
}

var file_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ui_proto_goTypes = []any{
	(*FieldUi)(nil),                   // 0: bor.ui.FieldUi
	(*IntOption)(nil),                 // 1: bor.ui.IntOption
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
}
var file_ui_proto_depIdxs = []int32{
	1, // 0: bor.ui.FieldUi.int_options:type_name -> bor.ui.IntOption
	2, // 1: bor.ui.field:extendee -> google.protobuf.FieldOptions
	0, // 2: bor.ui.field:type_name -> bor.ui.FieldUi
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ui_proto_init() }
func file_ui_proto_init() {
	if File_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ui_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_ui_proto_goTypes,
		DependencyIndexes: file_ui_proto_depIdxs,
		MessageInfos:      file_ui_proto_msgTypes,
		ExtensionInfos:    file_ui_proto_extTypes,
	}.Build()
	File_ui_proto = out.File
	file_ui_proto_rawDesc = nil
	file_ui_proto_goTypes = nil
	file_ui_proto_depIdxs = nil
}
