// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Vute Tech LTD
// Copyright (C) 2026 Bor contributors

// protoc-gen-bor-ui is a protoc plugin that reads (bor.ui.field) annotations
// from *Policy messages and emits *_ui.ts files consumed by the Bor web UI.
//
// For each proto file containing a message whose name ends in "Policy", the
// plugin emits a <basename>_ui.ts file exporting a read-only array of
// PolicyFieldDef objects.  It also emits policy_ui_types.ts once, containing
// the shared TypeScript interface definitions.
//
// Run via:  make proto   (proto-ui target)
package main

import (
	"fmt"
	"path"
	"regexp"
	"strings"
	"unicode"

	borui "github.com/VuteTech/Bor/server/pkg/grpc/borui"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

// wordRe matches one word in a PascalCase/camelCase identifier.
// Pattern: one or more uppercase letters followed by zero or more lowercase
// letters — handles both "SSL" (pure acronym) and "URLs" (acronym + plural).
var wordRe = regexp.MustCompile(`[A-Z]+[a-z]*|[a-z]+`)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		sharedEmitted := false
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			policyMessages := collectPolicyMessages(f)
			if len(policyMessages) == 0 {
				continue
			}
			if !sharedEmitted {
				emitSharedTypes(gen)
				sharedEmitted = true
			}
			emitPolicyUI(gen, f, policyMessages)
		}
		return nil
	})
}

// collectPolicyMessages returns all messages in f whose name ends in "Policy".
func collectPolicyMessages(f *protogen.File) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range f.Messages {
		if strings.HasSuffix(string(m.Desc.Name()), "Policy") {
			out = append(out, m)
		}
	}
	return out
}

// ──────────────────────────────────────────────────────────────────────────────
// Shared type file
// ──────────────────────────────────────────────────────────────────────────────

func emitSharedTypes(gen *protogen.Plugin) {
	g := gen.NewGeneratedFile("policy_ui_types.ts", "")
	g.P(`// AUTO-GENERATED by protoc-gen-bor-ui. DO NOT EDIT.`)
	g.P()
	g.P(`export type PolicyFieldType =`)
	g.P(`  | "boolean"`)
	g.P(`  | "string"`)
	g.P(`  | "integer"`)
	g.P(`  | "string-enum"`)
	g.P(`  | "integer-enum"`)
	g.P(`  | "list"`)
	g.P(`  | "json"`)
	g.P(`  | "object";`)
	g.P()
	g.P(`export interface PolicySubFieldDef {`)
	g.P(`  key: string;`)
	g.P(`  label: string;`)
	g.P(`  description: string;`)
	g.P(`  type: Exclude<PolicyFieldType, "object" | "integer-enum" | "json">;`)
	g.P(`  stringOptions?: string[];`)
	g.P(`}`)
	g.P()
	g.P(`export interface PolicyFieldDef {`)
	g.P(`  key: string;`)
	g.P(`  label: string;`)
	g.P(`  group: string;`)
	g.P(`  description: string;`)
	g.P(`  type: PolicyFieldType;`)
	g.P(`  stringOptions?: string[];`)
	g.P(`  intOptions?: { value: number; label: string }[];`)
	g.P(`  subFields?: PolicySubFieldDef[];`)
	g.P(`  chromeOnly?: boolean;`)
	g.P(`}`)
}

// ──────────────────────────────────────────────────────────────────────────────
// Per-file policy UI file
// ──────────────────────────────────────────────────────────────────────────────

func emitPolicyUI(gen *protogen.Plugin, f *protogen.File, messages []*protogen.Message) {
	// Derive output name from the proto filename (e.g. "chrome.proto" → "chrome_ui.ts").
	// f.GeneratedFilenamePrefix contains the full Go package path; use Desc.Path() instead.
	baseName := strings.TrimSuffix(path.Base(f.Desc.Path()), ".proto")
	outName := baseName + "_ui.ts"

	g := gen.NewGeneratedFile(outName, "")
	g.P(`// AUTO-GENERATED by protoc-gen-bor-ui. DO NOT EDIT.`)
	g.P(`import type { PolicyFieldDef } from "./policy_ui_types";`)
	g.P()

	for _, msg := range messages {
		// e.g. ChromePolicy → CHROME_ALL_POLICIES
		constName := toScreamingSnake(string(msg.Desc.Name()))

		g.P(fmt.Sprintf("export const %s: readonly PolicyFieldDef[] = [", constName))
		for _, field := range msg.Fields {
			if !hasUIAnnotation(field) {
				continue
			}
			emitField(g, field, 1)
		}
		g.P(`];`)
		g.P()
	}
}

// toScreamingSnake converts "ChromePolicy" → "CHROME_ALL_POLICIES"
func toScreamingSnake(name string) string {
	// strip "Policy" suffix
	name = strings.TrimSuffix(name, "Policy")
	// split PascalCase → words
	var words []string
	var cur strings.Builder
	for i, r := range name {
		if i > 0 && unicode.IsUpper(r) {
			words = append(words, cur.String())
			cur.Reset()
		}
		cur.WriteRune(r)
	}
	if cur.Len() > 0 {
		words = append(words, cur.String())
	}
	return strings.ToUpper(strings.Join(words, "_")) + "_ALL_POLICIES"
}

// hasUIAnnotation returns true if the field has a (bor.ui.field) option with
// a non-empty group.
func hasUIAnnotation(field *protogen.Field) bool {
	opts := field.Desc.Options()
	if opts == nil {
		return false
	}
	if !proto.HasExtension(opts, borui.E_Field) {
		return false
	}
	ui, ok := proto.GetExtension(opts, borui.E_Field).(*borui.FieldUi)
	if !ok || ui == nil {
		return false
	}
	return ui.Group != "" || field.Desc.Kind() != protoreflect.MessageKind
}

// emitField writes one PolicyFieldDef entry.
func emitField(g *protogen.GeneratedFile, field *protogen.Field, indent int) {
	ui := getUI(field)
	key := field.Desc.JSONName()
	label := ui.GetLabel()
	if label == "" {
		label = derivedLabel(string(field.Desc.Name()))
	}
	description := ui.GetDescription()
	if description == "" {
		description = extractComment(field.Comments.Leading)
	}
	group := ui.GetGroup()
	fieldType := inferType(field, ui)

	pad := strings.Repeat("  ", indent)
	g.P(pad + "{")
	g.P(fmt.Sprintf("%s  key: %q,", pad, key))
	g.P(fmt.Sprintf("%s  label: %q,", pad, label))
	g.P(fmt.Sprintf("%s  group: %q,", pad, group))
	g.P(fmt.Sprintf("%s  description: %q,", pad, description))
	g.P(fmt.Sprintf("%s  type: %q,", pad, fieldType))

	switch fieldType {
	case "string-enum":
		emitStringOptions(g, ui.GetStringOptions(), pad)
	case "integer-enum":
		emitIntOptions(g, ui.GetIntOptions(), pad)
	case "object":
		emitSubFields(g, field, pad)
	}

	if ui.GetChromeOnly() {
		g.P(pad + "  chromeOnly: true,")
	}
	g.P(pad + "},")
}

func emitStringOptions(g *protogen.GeneratedFile, opts []string, pad string) {
	g.P(pad + "  stringOptions: [")
	for _, o := range opts {
		g.P(fmt.Sprintf("%s    %q,", pad, o))
	}
	g.P(pad + "  ],")
}

func emitIntOptions(g *protogen.GeneratedFile, opts []*borui.IntOption, pad string) {
	g.P(pad + "  intOptions: [")
	for _, o := range opts {
		g.P(fmt.Sprintf("%s    { value: %d, label: %q },", pad, o.GetValue(), o.GetLabel()))
	}
	g.P(pad + "  ],")
}

func emitSubFields(g *protogen.GeneratedFile, field *protogen.Field, pad string) {
	if field.Message == nil {
		return
	}
	g.P(pad + "  subFields: [")
	for _, sub := range field.Message.Fields {
		subUI := getUI(sub)
		subKey := sub.Desc.JSONName()
		subLabel := subUI.GetLabel()
		if subLabel == "" {
			subLabel = derivedLabel(string(sub.Desc.Name()))
		}
		subDesc := subUI.GetDescription()
		if subDesc == "" {
			subDesc = extractComment(sub.Comments.Leading)
		}
		subType := inferSubType(sub, subUI)

		g.P(pad + "    {")
		g.P(fmt.Sprintf("%s      key: %q,", pad, subKey))
		g.P(fmt.Sprintf("%s      label: %q,", pad, subLabel))
		g.P(fmt.Sprintf("%s      description: %q,", pad, subDesc))
		g.P(fmt.Sprintf("%s      type: %q,", pad, subType))
		if subType == "string-enum" && len(subUI.GetStringOptions()) > 0 {
			g.P(pad + "      stringOptions: [")
			for _, o := range subUI.GetStringOptions() {
				g.P(fmt.Sprintf("%s        %q,", pad, o))
			}
			g.P(pad + "      ],")
		}
		g.P(pad + "    },")
	}
	g.P(pad + "  ],")
}

// ──────────────────────────────────────────────────────────────────────────────
// Type inference
// ──────────────────────────────────────────────────────────────────────────────

func inferType(field *protogen.Field, ui *borui.FieldUi) string {
	if field.Desc.IsList() && field.Desc.Kind() == protoreflect.StringKind {
		return "list"
	}
	if field.Desc.IsList() {
		return "list"
	}
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.StringKind:
		if len(ui.GetStringOptions()) > 0 {
			return "string-enum"
		}
		return "string"
	case protoreflect.Int32Kind, protoreflect.Int64Kind,
		protoreflect.Sint32Kind, protoreflect.Sint64Kind,
		protoreflect.Uint32Kind, protoreflect.Uint64Kind:
		if len(ui.GetIntOptions()) > 0 {
			return "integer-enum"
		}
		return "integer"
	case protoreflect.MessageKind:
		if field.Message != nil && string(field.Message.Desc.FullName()) == "google.protobuf.Value" {
			return "json"
		}
		return "object"
	}
	return "string"
}

func inferSubType(field *protogen.Field, ui *borui.FieldUi) string {
	if field.Desc.IsList() {
		return "list"
	}
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.StringKind:
		if len(ui.GetStringOptions()) > 0 {
			return "string-enum"
		}
		return "string"
	}
	return "string"
}

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

func getUI(field *protogen.Field) *borui.FieldUi {
	opts := field.Desc.Options()
	if opts == nil {
		return &borui.FieldUi{}
	}
	if !proto.HasExtension(opts, borui.E_Field) {
		return &borui.FieldUi{}
	}
	ui, ok := proto.GetExtension(opts, borui.E_Field).(*borui.FieldUi)
	if !ok || ui == nil {
		return &borui.FieldUi{}
	}
	return ui
}

// derivedLabel splits a PascalCase/camelCase identifier into space-separated
// words using wordRe. Acronyms and their plural suffixes are kept together.
//
// Examples:
//
//	"HomepageLocation"      → "Homepage Location"
//	"SSLVersionMin"         → "SSL Version Min"
//	"RestoreOnStartupURLs"  → "Restore On Startup URLs"
//	"DnsOverHttpsMode"      → "Dns Over Https Mode"
func derivedLabel(name string) string {
	words := wordRe.FindAllString(name, -1)
	return strings.Join(words, " ")
}

// extractComment strips leading // and trims whitespace from a protogen comment.
func extractComment(c protogen.Comments) string {
	s := strings.TrimSpace(string(c))
	// Remove leading "// " or "//" from each line and join.
	lines := strings.Split(s, "\n")
	var out []string
	for _, l := range lines {
		l = strings.TrimSpace(l)
		l = strings.TrimPrefix(l, "//")
		l = strings.TrimSpace(l)
		if l != "" {
			out = append(out, l)
		}
	}
	return strings.Join(out, " ")
}
