// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v6.33.0
// source: chrome.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChromePolicy holds Chrome/Chromium browser enterprise policy settings.
// Content is a JSON object mapping Chrome policy names to their values.
// See https://chromeenterprise.google/policies/ for the full policy reference.
type ChromePolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON object with Chrome policy key-value pairs.
	// Keys are Chrome policy names (e.g. "HomepageLocation", "ExtensionInstallForcelist").
	// Applied to all Chrome/Chromium variants via managed policy directories.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChromePolicy) Reset() {
	*x = ChromePolicy{}
	mi := &file_chrome_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChromePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChromePolicy) ProtoMessage() {}

func (x *ChromePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_chrome_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChromePolicy.ProtoReflect.Descriptor instead.
func (*ChromePolicy) Descriptor() ([]byte, []int) {
	return file_chrome_proto_rawDescGZIP(), []int{0}
}

func (x *ChromePolicy) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_chrome_proto protoreflect.FileDescriptor

var file_chrome_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x28, 0x0a,
	0x0c, 0x43, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x75, 0x74, 0x65, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x42,
	0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chrome_proto_rawDescOnce sync.Once
	file_chrome_proto_rawDescData = file_chrome_proto_rawDesc
)

func file_chrome_proto_rawDescGZIP() []byte {
	file_chrome_proto_rawDescOnce.Do(func() {
		file_chrome_proto_rawDescData = protoimpl.X.CompressGZIP(file_chrome_proto_rawDescData)
	})
	return file_chrome_proto_rawDescData
}

var file_chrome_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chrome_proto_goTypes = []any{
	(*ChromePolicy)(nil), // 0: bor.policy.v1.ChromePolicy
}
var file_chrome_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chrome_proto_init() }
func file_chrome_proto_init() {
	if File_chrome_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chrome_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chrome_proto_goTypes,
		DependencyIndexes: file_chrome_proto_depIdxs,
		MessageInfos:      file_chrome_proto_msgTypes,
	}.Build()
	File_chrome_proto = out.File
	file_chrome_proto_rawDesc = nil
	file_chrome_proto_goTypes = nil
	file_chrome_proto_depIdxs = nil
}
