// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Vute Tech LTD
// Copyright (C) 2026 Bor contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v7.34.1
// source: dconf.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DConfEntry represents one GSettings key to enforce.
type DConfEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"` // e.g. "org.gnome.desktop.screensaver"
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                         // dconf path override; empty for non-relocatable schemas
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                           // e.g. "lock-enabled"
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                       // GVariant text format: "true", "'Adwaita'", "uint32 300"
	Lock          bool                   `protobuf:"varint,5,opt,name=lock,proto3" json:"lock,omitempty"`                        // add this key to the locks file (user cannot override)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DConfEntry) Reset() {
	*x = DConfEntry{}
	mi := &file_dconf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DConfEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DConfEntry) ProtoMessage() {}

func (x *DConfEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dconf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DConfEntry.ProtoReflect.Descriptor instead.
func (*DConfEntry) Descriptor() ([]byte, []int) {
	return file_dconf_proto_rawDescGZIP(), []int{0}
}

func (x *DConfEntry) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *DConfEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DConfEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DConfEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DConfEntry) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

// DConfPolicy is a list of GSettings settings to enforce on a node.
type DConfPolicy struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*DConfEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// db_name is the dconf system-db name. Defaults to "local" if empty,
	// writing into /etc/dconf/db/local.d/.
	DbName        string `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DConfPolicy) Reset() {
	*x = DConfPolicy{}
	mi := &file_dconf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DConfPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DConfPolicy) ProtoMessage() {}

func (x *DConfPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_dconf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DConfPolicy.ProtoReflect.Descriptor instead.
func (*DConfPolicy) Descriptor() ([]byte, []int) {
	return file_dconf_proto_rawDescGZIP(), []int{1}
}

func (x *DConfPolicy) GetEntries() []*DConfEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *DConfPolicy) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

// GSettingsEnumValue describes one value of a GSettings enum or flags type.
type GSettingsEnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nick          string                 `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`    // short identifier used in GVariant text, e.g. "prefer-dark"
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // integer value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GSettingsEnumValue) Reset() {
	*x = GSettingsEnumValue{}
	mi := &file_dconf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSettingsEnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSettingsEnumValue) ProtoMessage() {}

func (x *GSettingsEnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_dconf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSettingsEnumValue.ProtoReflect.Descriptor instead.
func (*GSettingsEnumValue) Descriptor() ([]byte, []int) {
	return file_dconf_proto_rawDescGZIP(), []int{2}
}

func (x *GSettingsEnumValue) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *GSettingsEnumValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// GSettingsKey describes one key within a GSettings schema, including all
// metadata read from the schema XML on the agent node.
type GSettingsKey struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // key name, e.g. "lock-enabled"
	Type         string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                     // GVariant type code: "b", "s", "u", "i", "d", "as", …
	Summary      string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                               // short human-readable label  (from <summary>)
	Description  string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                       // long human-readable explanation (from <description>)
	DefaultValue string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // GVariant text format default, e.g. "true", "'Adwaita'"
	// For enum / flags types (<enum> or <flags> element in the schema XML).
	EnumValues []*GSettingsEnumValue `protobuf:"bytes,6,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	// For numeric types with a <range> constraint.
	RangeMin string `protobuf:"bytes,7,opt,name=range_min,json=rangeMin,proto3" json:"range_min,omitempty"` // GVariant text, e.g. "0"
	RangeMax string `protobuf:"bytes,8,opt,name=range_max,json=rangeMax,proto3" json:"range_max,omitempty"` // GVariant text, e.g. "4294967295"
	// For string keys with a fixed set of <choices>.
	Choices       []string `protobuf:"bytes,9,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GSettingsKey) Reset() {
	*x = GSettingsKey{}
	mi := &file_dconf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSettingsKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSettingsKey) ProtoMessage() {}

func (x *GSettingsKey) ProtoReflect() protoreflect.Message {
	mi := &file_dconf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSettingsKey.ProtoReflect.Descriptor instead.
func (*GSettingsKey) Descriptor() ([]byte, []int) {
	return file_dconf_proto_rawDescGZIP(), []int{3}
}

func (x *GSettingsKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GSettingsKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GSettingsKey) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GSettingsKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GSettingsKey) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *GSettingsKey) GetEnumValues() []*GSettingsEnumValue {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *GSettingsKey) GetRangeMin() string {
	if x != nil {
		return x.RangeMin
	}
	return ""
}

func (x *GSettingsKey) GetRangeMax() string {
	if x != nil {
		return x.RangeMax
	}
	return ""
}

func (x *GSettingsKey) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

// GSettingsSchema describes one schema available on the reporting node.
type GSettingsSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"` // e.g. "org.gnome.desktop.screensaver"
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                         // fixed dconf path; empty if relocatable
	Relocatable   bool                   `protobuf:"varint,3,opt,name=relocatable,proto3" json:"relocatable,omitempty"`          // true when path is not fixed
	Keys          []*GSettingsKey        `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GSettingsSchema) Reset() {
	*x = GSettingsSchema{}
	mi := &file_dconf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSettingsSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSettingsSchema) ProtoMessage() {}

func (x *GSettingsSchema) ProtoReflect() protoreflect.Message {
	mi := &file_dconf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSettingsSchema.ProtoReflect.Descriptor instead.
func (*GSettingsSchema) Descriptor() ([]byte, []int) {
	return file_dconf_proto_rawDescGZIP(), []int{4}
}

func (x *GSettingsSchema) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *GSettingsSchema) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GSettingsSchema) GetRelocatable() bool {
	if x != nil {
		return x.Relocatable
	}
	return false
}

func (x *GSettingsSchema) GetKeys() []*GSettingsKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// ReportSchemaCatalogueRequest is sent by the agent at startup (and after
// package installs) to inform the server which GSettings schemas are
// available on this node.  The agent reads
// /usr/share/glib-2.0/schemas/*.gschema.xml to build the list.
type ReportSchemaCatalogueRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Schemas  []*GSettingsSchema     `protobuf:"bytes,2,rep,name=schemas,proto3" json:"schemas,omitempty"`
	// Informational: GNOME version string if detectable, e.g. "46".
	GnomeVersion  string `protobuf:"bytes,3,opt,name=gnome_version,json=gnomeVersion,proto3" json:"gnome_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSchemaCatalogueRequest) Reset() {
	*x = ReportSchemaCatalogueRequest{}
	mi := &file_dconf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSchemaCatalogueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSchemaCatalogueRequest) ProtoMessage() {}

func (x *ReportSchemaCatalogueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dconf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSchemaCatalogueRequest.ProtoReflect.Descriptor instead.
func (*ReportSchemaCatalogueRequest) Descriptor() ([]byte, []int) {
	return file_dconf_proto_rawDescGZIP(), []int{5}
}

func (x *ReportSchemaCatalogueRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReportSchemaCatalogueRequest) GetSchemas() []*GSettingsSchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *ReportSchemaCatalogueRequest) GetGnomeVersion() string {
	if x != nil {
		return x.GnomeVersion
	}
	return ""
}

type ReportSchemaCatalogueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSchemaCatalogueResponse) Reset() {
	*x = ReportSchemaCatalogueResponse{}
	mi := &file_dconf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSchemaCatalogueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSchemaCatalogueResponse) ProtoMessage() {}

func (x *ReportSchemaCatalogueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dconf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSchemaCatalogueResponse.ProtoReflect.Descriptor instead.
func (*ReportSchemaCatalogueResponse) Descriptor() ([]byte, []int) {
	return file_dconf_proto_rawDescGZIP(), []int{6}
}

var File_dconf_proto protoreflect.FileDescriptor

var file_dconf_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62,
	0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x79, 0x0a, 0x0a,
	0x44, 0x43, 0x6f, 0x6e, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x5b, 0x0a, 0x0b, 0x44, 0x43, 0x6f, 0x6e, 0x66,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x43, 0x6f, 0x6e, 0x66, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x64,
	0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x12, 0x47, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0xaf, 0x02, 0x0a, 0x0c, 0x47, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x42,
	0x0a, 0x0b, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x6e, 0x75,
	0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x0f, 0x47, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2f, 0x0a,
	0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6f,
	0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x9a,
	0x01, 0x0a, 0x1c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x43,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x07,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x07, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x67, 0x6e, 0x6f, 0x6d, 0x65, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67,
	0x6e, 0x6f, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x1d, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x75, 0x74, 0x65, 0x54,
	0x65, 0x63, 0x68, 0x2f, 0x42, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3b, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dconf_proto_rawDescOnce sync.Once
	file_dconf_proto_rawDescData = file_dconf_proto_rawDesc
)

func file_dconf_proto_rawDescGZIP() []byte {
	file_dconf_proto_rawDescOnce.Do(func() {
		file_dconf_proto_rawDescData = protoimpl.X.CompressGZIP(file_dconf_proto_rawDescData)
	})
	return file_dconf_proto_rawDescData
}

var file_dconf_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dconf_proto_goTypes = []any{
	(*DConfEntry)(nil),                    // 0: bor.policy.v1.DConfEntry
	(*DConfPolicy)(nil),                   // 1: bor.policy.v1.DConfPolicy
	(*GSettingsEnumValue)(nil),            // 2: bor.policy.v1.GSettingsEnumValue
	(*GSettingsKey)(nil),                  // 3: bor.policy.v1.GSettingsKey
	(*GSettingsSchema)(nil),               // 4: bor.policy.v1.GSettingsSchema
	(*ReportSchemaCatalogueRequest)(nil),  // 5: bor.policy.v1.ReportSchemaCatalogueRequest
	(*ReportSchemaCatalogueResponse)(nil), // 6: bor.policy.v1.ReportSchemaCatalogueResponse
}
var file_dconf_proto_depIdxs = []int32{
	0, // 0: bor.policy.v1.DConfPolicy.entries:type_name -> bor.policy.v1.DConfEntry
	2, // 1: bor.policy.v1.GSettingsKey.enum_values:type_name -> bor.policy.v1.GSettingsEnumValue
	3, // 2: bor.policy.v1.GSettingsSchema.keys:type_name -> bor.policy.v1.GSettingsKey
	4, // 3: bor.policy.v1.ReportSchemaCatalogueRequest.schemas:type_name -> bor.policy.v1.GSettingsSchema
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dconf_proto_init() }
func file_dconf_proto_init() {
	if File_dconf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dconf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dconf_proto_goTypes,
		DependencyIndexes: file_dconf_proto_depIdxs,
		MessageInfos:      file_dconf_proto_msgTypes,
	}.Build()
	File_dconf_proto = out.File
	file_dconf_proto_rawDesc = nil
	file_dconf_proto_goTypes = nil
	file_dconf_proto_depIdxs = nil
}
