// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Vute Tech LTD
// Copyright (C) 2026 Bor contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v7.34.1
// source: firewalld.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FirewalldPolicy manages the ruleset of a single firewalld zone on a node.
// Bor renders these settings into the zone's permanent XML
// (/etc/firewalld/zones/<zone>.xml), preserving any host-specific
// <interface>/<source> bindings, then reloads firewalld. Multiple bound
// FirewalldPolicies targeting the same zone are merged: list fields are unioned
// and scalar fields are won by the highest-priority binding.
//
// Note: this manages a firewalld *zone*, not a firewalld "policy object"
// (zone-to-zone forwarding), which is a separate, deferred feature.
type FirewalldPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target zone whose ruleset Bor manages. Empty = the node's default zone.
	Zone string `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	// Default packet target for the zone: "default" | "ACCEPT" | "REJECT" | "DROP".
	// Empty is treated as "default".
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Allowed services by name (see firewall-cmd --get-services), e.g. "ssh".
	Services []string `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	// Allowed ports.
	Ports []*FirewalldPort `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	// Allowed source ports.
	SourcePorts []*FirewalldPort `protobuf:"bytes,5,rep,name=source_ports,json=sourcePorts,proto3" json:"source_ports,omitempty"`
	// Allowed protocols from /etc/protocols, e.g. "gre", "esp".
	Protocols []string `protobuf:"bytes,6,rep,name=protocols,proto3" json:"protocols,omitempty"`
	// ICMP types to block by name (see firewall-cmd --get-icmptypes).
	IcmpBlocks []string `protobuf:"bytes,7,rep,name=icmp_blocks,json=icmpBlocks,proto3" json:"icmp_blocks,omitempty"`
	// Invert ICMP block handling: when true, only the listed icmp_blocks are
	// accepted and all other ICMP is blocked.
	IcmpBlockInversion bool `protobuf:"varint,8,opt,name=icmp_block_inversion,json=icmpBlockInversion,proto3" json:"icmp_block_inversion,omitempty"`
	// Enable masquerading (NAT) for the zone.
	Masquerade bool `protobuf:"varint,9,opt,name=masquerade,proto3" json:"masquerade,omitempty"`
	// Port forwards.
	ForwardPorts []*FirewalldForwardPort `protobuf:"bytes,10,rep,name=forward_ports,json=forwardPorts,proto3" json:"forward_ports,omitempty"`
	// Raw firewalld rich-language rule strings, for rules not expressible above.
	// Example: rule family="ipv4" source address="10.0.0.0/8" service name="ssh" accept
	RichRules []string `protobuf:"bytes,11,rep,name=rich_rules,json=richRules,proto3" json:"rich_rules,omitempty"`
	// Phase 2: when true, the agent ensures firewalld is enabled and running
	// before applying. When false (default) and firewalld is inactive, the
	// policy is reported INAPPLICABLE. Not yet enforced.
	EnsureEnabled bool `protobuf:"varint,12,opt,name=ensure_enabled,json=ensureEnabled,proto3" json:"ensure_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewalldPolicy) Reset() {
	*x = FirewalldPolicy{}
	mi := &file_firewalld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewalldPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewalldPolicy) ProtoMessage() {}

func (x *FirewalldPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_firewalld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewalldPolicy.ProtoReflect.Descriptor instead.
func (*FirewalldPolicy) Descriptor() ([]byte, []int) {
	return file_firewalld_proto_rawDescGZIP(), []int{0}
}

func (x *FirewalldPolicy) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *FirewalldPolicy) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FirewalldPolicy) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *FirewalldPolicy) GetPorts() []*FirewalldPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *FirewalldPolicy) GetSourcePorts() []*FirewalldPort {
	if x != nil {
		return x.SourcePorts
	}
	return nil
}

func (x *FirewalldPolicy) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *FirewalldPolicy) GetIcmpBlocks() []string {
	if x != nil {
		return x.IcmpBlocks
	}
	return nil
}

func (x *FirewalldPolicy) GetIcmpBlockInversion() bool {
	if x != nil {
		return x.IcmpBlockInversion
	}
	return false
}

func (x *FirewalldPolicy) GetMasquerade() bool {
	if x != nil {
		return x.Masquerade
	}
	return false
}

func (x *FirewalldPolicy) GetForwardPorts() []*FirewalldForwardPort {
	if x != nil {
		return x.ForwardPorts
	}
	return nil
}

func (x *FirewalldPolicy) GetRichRules() []string {
	if x != nil {
		return x.RichRules
	}
	return nil
}

func (x *FirewalldPolicy) GetEnsureEnabled() bool {
	if x != nil {
		return x.EnsureEnabled
	}
	return false
}

// FirewalldPort is a single port or port range with its protocol.
type FirewalldPort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Port id "443" or range "5000-6000".
	Port string `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	// Transport protocol: "tcp" | "udp" | "sctp" | "dccp".
	Protocol      string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewalldPort) Reset() {
	*x = FirewalldPort{}
	mi := &file_firewalld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewalldPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewalldPort) ProtoMessage() {}

func (x *FirewalldPort) ProtoReflect() protoreflect.Message {
	mi := &file_firewalld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewalldPort.ProtoReflect.Descriptor instead.
func (*FirewalldPort) Descriptor() ([]byte, []int) {
	return file_firewalld_proto_rawDescGZIP(), []int{1}
}

func (x *FirewalldPort) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *FirewalldPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// FirewalldForwardPort describes a port-forwarding rule.
type FirewalldForwardPort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source port id or range.
	Port string `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	// Transport protocol: "tcp" | "udp" | "sctp" | "dccp".
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Destination port (defaults to the source port when empty).
	ToPort string `protobuf:"bytes,3,opt,name=to_port,json=toPort,proto3" json:"to_port,omitempty"`
	// Destination address for remote forwarding (optional).
	ToAddr        string `protobuf:"bytes,4,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewalldForwardPort) Reset() {
	*x = FirewalldForwardPort{}
	mi := &file_firewalld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewalldForwardPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewalldForwardPort) ProtoMessage() {}

func (x *FirewalldForwardPort) ProtoReflect() protoreflect.Message {
	mi := &file_firewalld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewalldForwardPort.ProtoReflect.Descriptor instead.
func (*FirewalldForwardPort) Descriptor() ([]byte, []int) {
	return file_firewalld_proto_rawDescGZIP(), []int{2}
}

func (x *FirewalldForwardPort) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *FirewalldForwardPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FirewalldForwardPort) GetToPort() string {
	if x != nil {
		return x.ToPort
	}
	return ""
}

func (x *FirewalldForwardPort) GetToAddr() string {
	if x != nil {
		return x.ToAddr
	}
	return ""
}

var File_firewalld_proto protoreflect.FileDescriptor

var file_firewalld_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31,
	0x22, 0xef, 0x03, 0x0a, 0x0f, 0x46, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x64, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x05,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f,
	0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x72, 0x65,
	0x77, 0x61, 0x6c, 0x6c, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x12, 0x3f, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x64,
	0x50, 0x6f, 0x72, 0x74, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x63, 0x6d, 0x70, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x63, 0x6d, 0x70, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x12, 0x30, 0x0a, 0x14, 0x69, 0x63, 0x6d, 0x70, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12,
	0x69, 0x63, 0x6d, 0x70, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x73, 0x71, 0x75, 0x65, 0x72, 0x61, 0x64, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6d, 0x61, 0x73, 0x71, 0x75, 0x65, 0x72, 0x61,
	0x64, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x62, 0x6f, 0x72, 0x2e,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x72, 0x65, 0x77, 0x61,
	0x6c, 0x6c, 0x64, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x0c,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x69, 0x63, 0x68, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x69, 0x63, 0x68, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x65,
	0x6e, 0x73, 0x75, 0x72, 0x65, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0d, 0x65, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x22, 0x3f, 0x0a, 0x0d, 0x46, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x64, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x22, 0x78, 0x0a, 0x14, 0x46, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x64,
	0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x6f, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x42, 0x37, 0x5a,
	0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x75, 0x74, 0x65,
	0x54, 0x65, 0x63, 0x68, 0x2f, 0x42, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3b,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_firewalld_proto_rawDescOnce sync.Once
	file_firewalld_proto_rawDescData = file_firewalld_proto_rawDesc
)

func file_firewalld_proto_rawDescGZIP() []byte {
	file_firewalld_proto_rawDescOnce.Do(func() {
		file_firewalld_proto_rawDescData = protoimpl.X.CompressGZIP(file_firewalld_proto_rawDescData)
	})
	return file_firewalld_proto_rawDescData
}

var file_firewalld_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_firewalld_proto_goTypes = []any{
	(*FirewalldPolicy)(nil),      // 0: bor.policy.v1.FirewalldPolicy
	(*FirewalldPort)(nil),        // 1: bor.policy.v1.FirewalldPort
	(*FirewalldForwardPort)(nil), // 2: bor.policy.v1.FirewalldForwardPort
}
var file_firewalld_proto_depIdxs = []int32{
	1, // 0: bor.policy.v1.FirewalldPolicy.ports:type_name -> bor.policy.v1.FirewalldPort
	1, // 1: bor.policy.v1.FirewalldPolicy.source_ports:type_name -> bor.policy.v1.FirewalldPort
	2, // 2: bor.policy.v1.FirewalldPolicy.forward_ports:type_name -> bor.policy.v1.FirewalldForwardPort
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_firewalld_proto_init() }
func file_firewalld_proto_init() {
	if File_firewalld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_firewalld_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_firewalld_proto_goTypes,
		DependencyIndexes: file_firewalld_proto_depIdxs,
		MessageInfos:      file_firewalld_proto_msgTypes,
	}.Build()
	File_firewalld_proto = out.File
	file_firewalld_proto_rawDesc = nil
	file_firewalld_proto_goTypes = nil
	file_firewalld_proto_depIdxs = nil
}
