// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v6.33.0
// source: kconfig.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KConfigEntry represents a single KDE Kiosk configuration entry.
type KConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Enforced      bool                   `protobuf:"varint,6,opt,name=enforced,proto3" json:"enforced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KConfigEntry) Reset() {
	*x = KConfigEntry{}
	mi := &file_kconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KConfigEntry) ProtoMessage() {}

func (x *KConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KConfigEntry.ProtoReflect.Descriptor instead.
func (*KConfigEntry) Descriptor() ([]byte, []int) {
	return file_kconfig_proto_rawDescGZIP(), []int{0}
}

func (x *KConfigEntry) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *KConfigEntry) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *KConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KConfigEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KConfigEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KConfigEntry) GetEnforced() bool {
	if x != nil {
		return x.Enforced
	}
	return false
}

// KConfigPolicy holds all KConfig entries for a single policy.
type KConfigPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KConfigEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KConfigPolicy) Reset() {
	*x = KConfigPolicy{}
	mi := &file_kconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KConfigPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KConfigPolicy) ProtoMessage() {}

func (x *KConfigPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_kconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KConfigPolicy.ProtoReflect.Descriptor instead.
func (*KConfigPolicy) Descriptor() ([]byte, []int) {
	return file_kconfig_proto_rawDescGZIP(), []int{1}
}

func (x *KConfigPolicy) GetEntries() []*KConfigEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_kconfig_proto protoreflect.FileDescriptor

var file_kconfig_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x90,
	0x01, 0x0a, 0x0c, 0x4b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x64, 0x22, 0x46, 0x0a, 0x0d, 0x4b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x12, 0x35, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x75, 0x74, 0x65, 0x54, 0x65, 0x63, 0x68,
	0x2f, 0x42, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3b, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kconfig_proto_rawDescOnce sync.Once
	file_kconfig_proto_rawDescData = file_kconfig_proto_rawDesc
)

func file_kconfig_proto_rawDescGZIP() []byte {
	file_kconfig_proto_rawDescOnce.Do(func() {
		file_kconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_kconfig_proto_rawDescData)
	})
	return file_kconfig_proto_rawDescData
}

var file_kconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kconfig_proto_goTypes = []any{
	(*KConfigEntry)(nil),  // 0: bor.policy.v1.KConfigEntry
	(*KConfigPolicy)(nil), // 1: bor.policy.v1.KConfigPolicy
}
var file_kconfig_proto_depIdxs = []int32{
	0, // 0: bor.policy.v1.KConfigPolicy.entries:type_name -> bor.policy.v1.KConfigEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kconfig_proto_init() }
func file_kconfig_proto_init() {
	if File_kconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kconfig_proto_goTypes,
		DependencyIndexes: file_kconfig_proto_depIdxs,
		MessageInfos:      file_kconfig_proto_msgTypes,
	}.Build()
	File_kconfig_proto = out.File
	file_kconfig_proto_rawDesc = nil
	file_kconfig_proto_goTypes = nil
	file_kconfig_proto_depIdxs = nil
}
