// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Vute Tech LTD
// Copyright (C) 2026 Bor contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v7.34.1
// source: package.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RepositoryType selects the target file format and directory on the agent node.
type RepositoryType int32

const (
	RepositoryType_REPOSITORY_TYPE_UNSPECIFIED RepositoryType = 0
	// APT deb822 format → /etc/apt/sources.list.d/bor-<id>.sources
	RepositoryType_REPOSITORY_TYPE_APT_DEB822 RepositoryType = 1
	// DNF/YUM INI format → /etc/yum.repos.d/bor-<id>.repo
	RepositoryType_REPOSITORY_TYPE_DNF RepositoryType = 2
	// Zypper INI format → /etc/zypp/repos.d/bor-<id>.repo
	RepositoryType_REPOSITORY_TYPE_ZYPPER RepositoryType = 3
)

// Enum value maps for RepositoryType.
var (
	RepositoryType_name = map[int32]string{
		0: "REPOSITORY_TYPE_UNSPECIFIED",
		1: "REPOSITORY_TYPE_APT_DEB822",
		2: "REPOSITORY_TYPE_DNF",
		3: "REPOSITORY_TYPE_ZYPPER",
	}
	RepositoryType_value = map[string]int32{
		"REPOSITORY_TYPE_UNSPECIFIED": 0,
		"REPOSITORY_TYPE_APT_DEB822":  1,
		"REPOSITORY_TYPE_DNF":         2,
		"REPOSITORY_TYPE_ZYPPER":      3,
	}
)

func (x RepositoryType) Enum() *RepositoryType {
	p := new(RepositoryType)
	*p = x
	return p
}

func (x RepositoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepositoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_package_proto_enumTypes[0].Descriptor()
}

func (RepositoryType) Type() protoreflect.EnumType {
	return &file_package_proto_enumTypes[0]
}

func (x RepositoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepositoryType.Descriptor instead.
func (RepositoryType) EnumDescriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{0}
}

// PackageState mirrors Ansible's state field for idempotent package management.
type PackageState int32

const (
	PackageState_PACKAGE_STATE_UNSPECIFIED PackageState = 0
	// Package must be installed at any version (or the pinned version if set).
	PackageState_PACKAGE_STATE_PRESENT PackageState = 1
	// Package must not be installed.
	PackageState_PACKAGE_STATE_ABSENT PackageState = 2
	// Package must be installed at the latest available version.
	PackageState_PACKAGE_STATE_LATEST PackageState = 3
)

// Enum value maps for PackageState.
var (
	PackageState_name = map[int32]string{
		0: "PACKAGE_STATE_UNSPECIFIED",
		1: "PACKAGE_STATE_PRESENT",
		2: "PACKAGE_STATE_ABSENT",
		3: "PACKAGE_STATE_LATEST",
	}
	PackageState_value = map[string]int32{
		"PACKAGE_STATE_UNSPECIFIED": 0,
		"PACKAGE_STATE_PRESENT":     1,
		"PACKAGE_STATE_ABSENT":      2,
		"PACKAGE_STATE_LATEST":      3,
	}
)

func (x PackageState) Enum() *PackageState {
	p := new(PackageState)
	*p = x
	return p
}

func (x PackageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageState) Descriptor() protoreflect.EnumDescriptor {
	return file_package_proto_enumTypes[1].Descriptor()
}

func (PackageState) Type() protoreflect.EnumType {
	return &file_package_proto_enumTypes[1]
}

func (x PackageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageState.Descriptor instead.
func (PackageState) EnumDescriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{1}
}

// RepositoryEntry describes one package repository source to be managed on
// the agent node. Repository files are named bor-<id>.{sources,repo} and
// written by the agent; the file watcher restores them if tampered.
type RepositoryEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier within the policy — used as the filename stem.
	// Must match ^[a-z0-9][a-z0-9_-]*$
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable label written as a comment in the generated file.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Target file format and package manager.
	Type RepositoryType `protobuf:"varint,3,opt,name=type,proto3,enum=bor.policy.v1.RepositoryType" json:"type,omitempty"`
	// Whether the repository is active. false writes enabled=0 / Enabled: no
	// rather than deleting the file, so the admin can re-enable it easily.
	Enabled bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Repository URI, e.g. "https://packages.example.com/apt"
	AptUri string `protobuf:"bytes,10,opt,name=apt_uri,json=aptUri,proto3" json:"apt_uri,omitempty"`
	// Distribution suite, e.g. "bookworm" or "jammy"
	AptSuites string `protobuf:"bytes,11,opt,name=apt_suites,json=aptSuites,proto3" json:"apt_suites,omitempty"`
	// Space-separated components, e.g. "main contrib non-free"
	AptComponents string `protobuf:"bytes,12,opt,name=apt_components,json=aptComponents,proto3" json:"apt_components,omitempty"`
	// Comma-separated architecture restriction, e.g. "amd64,arm64". Empty = all.
	AptArchitectures string `protobuf:"bytes,13,opt,name=apt_architectures,json=aptArchitectures,proto3" json:"apt_architectures,omitempty"`
	// Base URL. For DNF this may be multiple newline-separated mirrors.
	Baseurl string `protobuf:"bytes,20,opt,name=baseurl,proto3" json:"baseurl,omitempty"`
	// DNF mirrorlist URL. Mutually exclusive with baseurl.
	Mirrorlist string `protobuf:"bytes,21,opt,name=mirrorlist,proto3" json:"mirrorlist,omitempty"`
	// DNF: metadata expiry in seconds. 0 uses the backend default (21600).
	MetadataExpire int32 `protobuf:"varint,22,opt,name=metadata_expire,json=metadataExpire,proto3" json:"metadata_expire,omitempty"`
	// Zypper: repository priority (1=highest … 99=lowest). 0 uses default (99).
	ZypperPriority int32 `protobuf:"varint,23,opt,name=zypper_priority,json=zypperPriority,proto3" json:"zypper_priority,omitempty"`
	// Require package signature verification. Strongly recommended; set to
	// false only when the upstream repo does not sign packages. Setting false
	// generates a NON_COMPLIANT compliance item as a persistent reminder.
	GpgCheck bool `protobuf:"varint,30,opt,name=gpg_check,json=gpgCheck,proto3" json:"gpg_check,omitempty"`
	// Full 40-character hex fingerprint of the signing key, used to verify
	// the imported key matches what the admin intended. Fingerprints shorter
	// than 40 chars (MD5/SHA-1) are rejected server-side (FIPS 140-3).
	GpgKeyId string `protobuf:"bytes,31,opt,name=gpg_key_id,json=gpgKeyId,proto3" json:"gpg_key_id,omitempty"`
	// Binary GPG public key (base64-encoded in JSON transport).
	//
	//	APT:         written to /etc/apt/trusted.gpg.d/bor-<id>.gpg
	//	DNF/Zypper:  written to /etc/pki/rpm-gpg/bor-<id>.gpg and
	//	             referenced via gpgkey=file:// in the .repo file.
	GpgKeyData    []byte `protobuf:"bytes,32,opt,name=gpg_key_data,json=gpgKeyData,proto3" json:"gpg_key_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryEntry) Reset() {
	*x = RepositoryEntry{}
	mi := &file_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryEntry) ProtoMessage() {}

func (x *RepositoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryEntry.ProtoReflect.Descriptor instead.
func (*RepositoryEntry) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{0}
}

func (x *RepositoryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RepositoryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepositoryEntry) GetType() RepositoryType {
	if x != nil {
		return x.Type
	}
	return RepositoryType_REPOSITORY_TYPE_UNSPECIFIED
}

func (x *RepositoryEntry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RepositoryEntry) GetAptUri() string {
	if x != nil {
		return x.AptUri
	}
	return ""
}

func (x *RepositoryEntry) GetAptSuites() string {
	if x != nil {
		return x.AptSuites
	}
	return ""
}

func (x *RepositoryEntry) GetAptComponents() string {
	if x != nil {
		return x.AptComponents
	}
	return ""
}

func (x *RepositoryEntry) GetAptArchitectures() string {
	if x != nil {
		return x.AptArchitectures
	}
	return ""
}

func (x *RepositoryEntry) GetBaseurl() string {
	if x != nil {
		return x.Baseurl
	}
	return ""
}

func (x *RepositoryEntry) GetMirrorlist() string {
	if x != nil {
		return x.Mirrorlist
	}
	return ""
}

func (x *RepositoryEntry) GetMetadataExpire() int32 {
	if x != nil {
		return x.MetadataExpire
	}
	return 0
}

func (x *RepositoryEntry) GetZypperPriority() int32 {
	if x != nil {
		return x.ZypperPriority
	}
	return 0
}

func (x *RepositoryEntry) GetGpgCheck() bool {
	if x != nil {
		return x.GpgCheck
	}
	return false
}

func (x *RepositoryEntry) GetGpgKeyId() string {
	if x != nil {
		return x.GpgKeyId
	}
	return ""
}

func (x *RepositoryEntry) GetGpgKeyData() []byte {
	if x != nil {
		return x.GpgKeyData
	}
	return nil
}

// PackageEntry declares the desired installation state of a single package.
// The name is resolved by PackageKit on each node — a single policy covers
// all supported package managers (APT, DNF, Zypper) without per-distro variants.
type PackageEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package name as recognised by the local package database.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Desired installation state.
	State PackageState `protobuf:"varint,2,opt,name=state,proto3,enum=bor.policy.v1.PackageState" json:"state,omitempty"`
	// Optional version pin. Only meaningful with state=PRESENT; ignored for
	// ABSENT and LATEST. The agent checks the installed version against this
	// value and reports NON_COMPLIANT if they differ.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// When true, a package that cannot be found in any enabled repository
	// maps to INAPPLICABLE rather than NON_COMPLIANT. Use for optional
	// software that may not be available on all distributions.
	Optional      bool `protobuf:"varint,4,opt,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageEntry) Reset() {
	*x = PackageEntry{}
	mi := &file_package_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageEntry) ProtoMessage() {}

func (x *PackageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageEntry.ProtoReflect.Descriptor instead.
func (*PackageEntry) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{1}
}

func (x *PackageEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageEntry) GetState() PackageState {
	if x != nil {
		return x.State
	}
	return PackageState_PACKAGE_STATE_UNSPECIFIED
}

func (x *PackageEntry) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageEntry) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

// PackagePolicy manages package repositories and package installation state.
// Repositories are always applied before packages. Both sections are
// optional — a policy may contain only repositories, only packages, or both.
type PackagePolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repository entries to manage. Applied and written as files before
	// package operations begin. Deduplicated by id when merging.
	Repositories []*RepositoryEntry `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	// Package entries to manage via PackageKit D-Bus. Deduplicated by name
	// when merging; higher-priority policy wins for state and version.
	Packages []*PackageEntry `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	// Call PackageKit RefreshCache after writing repository files so that
	// newly added repos are immediately available for package resolution.
	// Default true; set false only when cache is managed externally.
	UpdateCache bool `protobuf:"varint,3,opt,name=update_cache,json=updateCache,proto3" json:"update_cache,omitempty"`
	// Allow PackageKit to downgrade an installed package to meet a version pin.
	AllowDowngrade bool `protobuf:"varint,4,opt,name=allow_downgrade,json=allowDowngrade,proto3" json:"allow_downgrade,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PackagePolicy) Reset() {
	*x = PackagePolicy{}
	mi := &file_package_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagePolicy) ProtoMessage() {}

func (x *PackagePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagePolicy.ProtoReflect.Descriptor instead.
func (*PackagePolicy) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{2}
}

func (x *PackagePolicy) GetRepositories() []*RepositoryEntry {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *PackagePolicy) GetPackages() []*PackageEntry {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PackagePolicy) GetUpdateCache() bool {
	if x != nil {
		return x.UpdateCache
	}
	return false
}

func (x *PackagePolicy) GetAllowDowngrade() bool {
	if x != nil {
		return x.AllowDowngrade
	}
	return false
}

var File_package_proto protoreflect.FileDescriptor

var file_package_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0xf7,
	0x03, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x74, 0x55, 0x72, 0x69, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x70, 0x74, 0x5f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x70, 0x74, 0x53, 0x75, 0x69, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x61,
	0x70, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x70, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x70, 0x74, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61,
	0x70, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x73, 0x65, 0x75, 0x72, 0x6c, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x75, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x69, 0x72,
	0x72, 0x6f, 0x72, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d,
	0x69, 0x72, 0x72, 0x6f, 0x72, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x16, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x7a, 0x79, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x17, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x7a, 0x79, 0x70,
	0x70, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x67,
	0x70, 0x67, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x67, 0x70, 0x67, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x0a, 0x67, 0x70, 0x67, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x70,
	0x67, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x70, 0x67, 0x5f, 0x6b, 0x65,
	0x79, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x20, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x67, 0x70,
	0x67, 0x4b, 0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62,
	0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x22, 0xd8, 0x01, 0x0a, 0x0d, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x42, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x08,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x44, 0x6f, 0x77, 0x6e, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x2a, 0x86, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x52, 0x45, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x4f,
	0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45, 0x50, 0x4f, 0x53, 0x49, 0x54,
	0x4f, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x50, 0x54, 0x5f, 0x44, 0x45, 0x42,
	0x38, 0x32, 0x32, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x50, 0x4f, 0x53, 0x49, 0x54,
	0x4f, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x4e, 0x46, 0x10, 0x02, 0x12, 0x1a,
	0x0a, 0x16, 0x52, 0x45, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x5a, 0x59, 0x50, 0x50, 0x45, 0x52, 0x10, 0x03, 0x2a, 0x7c, 0x0a, 0x0c, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x41,
	0x43, 0x4b, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x41, 0x43,
	0x4b, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x52, 0x45, 0x53, 0x45,
	0x4e, 0x54, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x42, 0x53, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x18,
	0x0a, 0x14, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x4c, 0x41, 0x54, 0x45, 0x53, 0x54, 0x10, 0x03, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x75, 0x74, 0x65, 0x54, 0x65, 0x63, 0x68, 0x2f,
	0x42, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3b, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_package_proto_rawDescOnce sync.Once
	file_package_proto_rawDescData = file_package_proto_rawDesc
)

func file_package_proto_rawDescGZIP() []byte {
	file_package_proto_rawDescOnce.Do(func() {
		file_package_proto_rawDescData = protoimpl.X.CompressGZIP(file_package_proto_rawDescData)
	})
	return file_package_proto_rawDescData
}

var file_package_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_package_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_package_proto_goTypes = []any{
	(RepositoryType)(0),     // 0: bor.policy.v1.RepositoryType
	(PackageState)(0),       // 1: bor.policy.v1.PackageState
	(*RepositoryEntry)(nil), // 2: bor.policy.v1.RepositoryEntry
	(*PackageEntry)(nil),    // 3: bor.policy.v1.PackageEntry
	(*PackagePolicy)(nil),   // 4: bor.policy.v1.PackagePolicy
}
var file_package_proto_depIdxs = []int32{
	0, // 0: bor.policy.v1.RepositoryEntry.type:type_name -> bor.policy.v1.RepositoryType
	1, // 1: bor.policy.v1.PackageEntry.state:type_name -> bor.policy.v1.PackageState
	2, // 2: bor.policy.v1.PackagePolicy.repositories:type_name -> bor.policy.v1.RepositoryEntry
	3, // 3: bor.policy.v1.PackagePolicy.packages:type_name -> bor.policy.v1.PackageEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_package_proto_init() }
func file_package_proto_init() {
	if File_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_package_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_package_proto_goTypes,
		DependencyIndexes: file_package_proto_depIdxs,
		EnumInfos:         file_package_proto_enumTypes,
		MessageInfos:      file_package_proto_msgTypes,
	}.Build()
	File_package_proto = out.File
	file_package_proto_rawDesc = nil
	file_package_proto_goTypes = nil
	file_package_proto_depIdxs = nil
}
