// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Vute Tech LTD
// Copyright (C) 2026 Bor contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v7.34.1
// source: polkit.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolkitResult is the authorization result returned by a matched rule.
type PolkitResult int32

const (
	PolkitResult_POLKIT_RESULT_NOT_SET         PolkitResult = 0 // rule disabled / skipped
	PolkitResult_POLKIT_RESULT_NO              PolkitResult = 1 // unconditionally deny
	PolkitResult_POLKIT_RESULT_YES             PolkitResult = 2 // unconditionally allow
	PolkitResult_POLKIT_RESULT_AUTH_SELF       PolkitResult = 3 // user authenticates as themselves
	PolkitResult_POLKIT_RESULT_AUTH_SELF_KEEP  PolkitResult = 4 // like AUTH_SELF, result cached ~5 min
	PolkitResult_POLKIT_RESULT_AUTH_ADMIN      PolkitResult = 5 // an administrator must authenticate
	PolkitResult_POLKIT_RESULT_AUTH_ADMIN_KEEP PolkitResult = 6 // like AUTH_ADMIN, result cached ~5 min
)

// Enum value maps for PolkitResult.
var (
	PolkitResult_name = map[int32]string{
		0: "POLKIT_RESULT_NOT_SET",
		1: "POLKIT_RESULT_NO",
		2: "POLKIT_RESULT_YES",
		3: "POLKIT_RESULT_AUTH_SELF",
		4: "POLKIT_RESULT_AUTH_SELF_KEEP",
		5: "POLKIT_RESULT_AUTH_ADMIN",
		6: "POLKIT_RESULT_AUTH_ADMIN_KEEP",
	}
	PolkitResult_value = map[string]int32{
		"POLKIT_RESULT_NOT_SET":         0,
		"POLKIT_RESULT_NO":              1,
		"POLKIT_RESULT_YES":             2,
		"POLKIT_RESULT_AUTH_SELF":       3,
		"POLKIT_RESULT_AUTH_SELF_KEEP":  4,
		"POLKIT_RESULT_AUTH_ADMIN":      5,
		"POLKIT_RESULT_AUTH_ADMIN_KEEP": 6,
	}
)

func (x PolkitResult) Enum() *PolkitResult {
	p := new(PolkitResult)
	*p = x
	return p
}

func (x PolkitResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolkitResult) Descriptor() protoreflect.EnumDescriptor {
	return file_polkit_proto_enumTypes[0].Descriptor()
}

func (PolkitResult) Type() protoreflect.EnumType {
	return &file_polkit_proto_enumTypes[0]
}

func (x PolkitResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolkitResult.Descriptor instead.
func (PolkitResult) EnumDescriptor() ([]byte, []int) {
	return file_polkit_proto_rawDescGZIP(), []int{0}
}

// PolkitPolicy produces a single JavaScript rules file under
// /etc/polkit-1/rules.d/.  Rules are evaluated top-to-bottom;
// first match wins (polkit semantics).
type PolkitPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rules to write into the generated .rules file.
	// Highest-priority policies come first so their rules win.
	Rules []*PolkitRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	// Two-digit filename prefix (default "50").
	// Produces /etc/polkit-1/rules.d/<file_prefix>-bor.rules.
	// Higher numbers run later (after other rule files with lower numbers).
	FilePrefix    string `protobuf:"bytes,2,opt,name=file_prefix,json=filePrefix,proto3" json:"file_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolkitPolicy) Reset() {
	*x = PolkitPolicy{}
	mi := &file_polkit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolkitPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolkitPolicy) ProtoMessage() {}

func (x *PolkitPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_polkit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolkitPolicy.ProtoReflect.Descriptor instead.
func (*PolkitPolicy) Descriptor() ([]byte, []int) {
	return file_polkit_proto_rawDescGZIP(), []int{0}
}

func (x *PolkitPolicy) GetRules() []*PolkitRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *PolkitPolicy) GetFilePrefix() string {
	if x != nil {
		return x.FilePrefix
	}
	return ""
}

// PolkitRule maps one or more polkit actions to a result for matching subjects.
// Generates a single polkit.addRule(...) call.
type PolkitRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable label shown in the UI and emitted as a JS comment.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Exact action IDs matched with: action.id == "..."
	// Combined with OR; at least one of action_ids / action_prefixes must be set.
	ActionIds []string `protobuf:"bytes,2,rep,name=action_ids,json=actionIds,proto3" json:"action_ids,omitempty"`
	// Action ID prefixes matched with: action.id.indexOf("...") === 0
	// Combined with OR.
	ActionPrefixes []string `protobuf:"bytes,3,rep,name=action_prefixes,json=actionPrefixes,proto3" json:"action_prefixes,omitempty"`
	// Subject filter — all set fields must match (AND logic).
	// An empty filter matches every subject.
	Subject *PolkitSubjectFilter `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	// Authorization result to return when the rule matches.
	Result        PolkitResult `protobuf:"varint,5,opt,name=result,proto3,enum=bor.policy.v1.PolkitResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolkitRule) Reset() {
	*x = PolkitRule{}
	mi := &file_polkit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolkitRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolkitRule) ProtoMessage() {}

func (x *PolkitRule) ProtoReflect() protoreflect.Message {
	mi := &file_polkit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolkitRule.ProtoReflect.Descriptor instead.
func (*PolkitRule) Descriptor() ([]byte, []int) {
	return file_polkit_proto_rawDescGZIP(), []int{1}
}

func (x *PolkitRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolkitRule) GetActionIds() []string {
	if x != nil {
		return x.ActionIds
	}
	return nil
}

func (x *PolkitRule) GetActionPrefixes() []string {
	if x != nil {
		return x.ActionPrefixes
	}
	return nil
}

func (x *PolkitRule) GetSubject() *PolkitSubjectFilter {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *PolkitRule) GetResult() PolkitResult {
	if x != nil {
		return x.Result
	}
	return PolkitResult_POLKIT_RESULT_NOT_SET
}

// PolkitSubjectFilter restricts a rule to subjects that satisfy all set fields.
type PolkitSubjectFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject must be a member of this Unix group (e.g. "wheel", "sudo").
	InGroup string `protobuf:"bytes,1,opt,name=in_group,json=inGroup,proto3" json:"in_group,omitempty"`
	// Negate the group check: apply when the subject is NOT in in_group.
	// Ignored when in_group is empty.
	NegateGroup bool `protobuf:"varint,2,opt,name=negate_group,json=negateGroup,proto3" json:"negate_group,omitempty"`
	// Subject username must equal this value exactly.
	IsUser string `protobuf:"bytes,3,opt,name=is_user,json=isUser,proto3" json:"is_user,omitempty"`
	// Subject must be on a local console seat (subject.local === true).
	RequireLocal bool `protobuf:"varint,4,opt,name=require_local,json=requireLocal,proto3" json:"require_local,omitempty"`
	// Subject must have an active session (subject.active === true).
	RequireActive bool `protobuf:"varint,5,opt,name=require_active,json=requireActive,proto3" json:"require_active,omitempty"`
	// Subject process must belong to this systemd unit.
	SystemUnit    string `protobuf:"bytes,6,opt,name=system_unit,json=systemUnit,proto3" json:"system_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolkitSubjectFilter) Reset() {
	*x = PolkitSubjectFilter{}
	mi := &file_polkit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolkitSubjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolkitSubjectFilter) ProtoMessage() {}

func (x *PolkitSubjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_polkit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolkitSubjectFilter.ProtoReflect.Descriptor instead.
func (*PolkitSubjectFilter) Descriptor() ([]byte, []int) {
	return file_polkit_proto_rawDescGZIP(), []int{2}
}

func (x *PolkitSubjectFilter) GetInGroup() string {
	if x != nil {
		return x.InGroup
	}
	return ""
}

func (x *PolkitSubjectFilter) GetNegateGroup() bool {
	if x != nil {
		return x.NegateGroup
	}
	return false
}

func (x *PolkitSubjectFilter) GetIsUser() string {
	if x != nil {
		return x.IsUser
	}
	return ""
}

func (x *PolkitSubjectFilter) GetRequireLocal() bool {
	if x != nil {
		return x.RequireLocal
	}
	return false
}

func (x *PolkitSubjectFilter) GetRequireActive() bool {
	if x != nil {
		return x.RequireActive
	}
	return false
}

func (x *PolkitSubjectFilter) GetSystemUnit() string {
	if x != nil {
		return x.SystemUnit
	}
	return ""
}

// PolkitActionDescription describes one polkit action installed on a node,
// as read from the action XML files under /usr/share/polkit-1/actions/.
type PolkitActionDescription struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActionId        string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // human-readable name
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`         // shown to the user during the auth prompt
	Vendor          string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	DefaultAny      string                 `protobuf:"bytes,5,opt,name=default_any,json=defaultAny,proto3" json:"default_any,omitempty"` // "no" | "yes" | "auth_self" | "auth_admin" | …
	DefaultInactive string                 `protobuf:"bytes,6,opt,name=default_inactive,json=defaultInactive,proto3" json:"default_inactive,omitempty"`
	DefaultActive   string                 `protobuf:"bytes,7,opt,name=default_active,json=defaultActive,proto3" json:"default_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolkitActionDescription) Reset() {
	*x = PolkitActionDescription{}
	mi := &file_polkit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolkitActionDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolkitActionDescription) ProtoMessage() {}

func (x *PolkitActionDescription) ProtoReflect() protoreflect.Message {
	mi := &file_polkit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolkitActionDescription.ProtoReflect.Descriptor instead.
func (*PolkitActionDescription) Descriptor() ([]byte, []int) {
	return file_polkit_proto_rawDescGZIP(), []int{3}
}

func (x *PolkitActionDescription) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *PolkitActionDescription) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolkitActionDescription) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PolkitActionDescription) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *PolkitActionDescription) GetDefaultAny() string {
	if x != nil {
		return x.DefaultAny
	}
	return ""
}

func (x *PolkitActionDescription) GetDefaultInactive() string {
	if x != nil {
		return x.DefaultInactive
	}
	return ""
}

func (x *PolkitActionDescription) GetDefaultActive() string {
	if x != nil {
		return x.DefaultActive
	}
	return ""
}

// ReportPolkitCatalogueRequest is sent by the agent at startup (and after
// package changes) to inform the server which polkit actions are available
// on this node.  Mirrors the GSettings schema catalogue pattern.
type ReportPolkitCatalogueRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ClientId      string                     `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Actions       []*PolkitActionDescription `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPolkitCatalogueRequest) Reset() {
	*x = ReportPolkitCatalogueRequest{}
	mi := &file_polkit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPolkitCatalogueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPolkitCatalogueRequest) ProtoMessage() {}

func (x *ReportPolkitCatalogueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polkit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPolkitCatalogueRequest.ProtoReflect.Descriptor instead.
func (*ReportPolkitCatalogueRequest) Descriptor() ([]byte, []int) {
	return file_polkit_proto_rawDescGZIP(), []int{4}
}

func (x *ReportPolkitCatalogueRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReportPolkitCatalogueRequest) GetActions() []*PolkitActionDescription {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ReportPolkitCatalogueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPolkitCatalogueResponse) Reset() {
	*x = ReportPolkitCatalogueResponse{}
	mi := &file_polkit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPolkitCatalogueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPolkitCatalogueResponse) ProtoMessage() {}

func (x *ReportPolkitCatalogueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polkit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPolkitCatalogueResponse.ProtoReflect.Descriptor instead.
func (*ReportPolkitCatalogueResponse) Descriptor() ([]byte, []int) {
	return file_polkit_proto_rawDescGZIP(), []int{5}
}

func (x *ReportPolkitCatalogueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_polkit_proto protoreflect.FileDescriptor

var file_polkit_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x60, 0x0a,
	0x0c, 0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x2f, 0x0a,
	0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62,
	0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c,
	0x6b, 0x69, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22,
	0xe9, 0x01, 0x0a, 0x0a, 0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x12,
	0x27, 0x0a, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x6f, 0x72, 0x2e,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74,
	0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x07, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xd9, 0x01, 0x0a, 0x13,
	0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21,
	0x0a, 0x0c, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12,
	0x25, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x55, 0x6e, 0x69, 0x74, 0x22, 0xfd, 0x01, 0x0a, 0x17, 0x50, 0x6f, 0x6c, 0x6b,
	0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x61, 0x6e, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x41, 0x6e, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x5f, 0x69, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x7d, 0x0a, 0x1c, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x39, 0x0a, 0x1d, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x2a, 0xd6, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x4f, 0x4c, 0x4b, 0x49, 0x54, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x14, 0x0a,
	0x10, 0x50, 0x4f, 0x4c, 0x4b, 0x49, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x4e,
	0x4f, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x4f, 0x4c, 0x4b, 0x49, 0x54, 0x5f, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x5f, 0x59, 0x45, 0x53, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x50, 0x4f,
	0x4c, 0x4b, 0x49, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x48,
	0x5f, 0x53, 0x45, 0x4c, 0x46, 0x10, 0x03, 0x12, 0x20, 0x0a, 0x1c, 0x50, 0x4f, 0x4c, 0x4b, 0x49,
	0x54, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x53, 0x45,
	0x4c, 0x46, 0x5f, 0x4b, 0x45, 0x45, 0x50, 0x10, 0x04, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4f, 0x4c,
	0x4b, 0x49, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f,
	0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x05, 0x12, 0x21, 0x0a, 0x1d, 0x50, 0x4f, 0x4c, 0x4b, 0x49,
	0x54, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x41, 0x44,
	0x4d, 0x49, 0x4e, 0x5f, 0x4b, 0x45, 0x45, 0x50, 0x10, 0x06, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x75, 0x74, 0x65, 0x54, 0x65, 0x63,
	0x68, 0x2f, 0x42, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3b, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_polkit_proto_rawDescOnce sync.Once
	file_polkit_proto_rawDescData = file_polkit_proto_rawDesc
)

func file_polkit_proto_rawDescGZIP() []byte {
	file_polkit_proto_rawDescOnce.Do(func() {
		file_polkit_proto_rawDescData = protoimpl.X.CompressGZIP(file_polkit_proto_rawDescData)
	})
	return file_polkit_proto_rawDescData
}

var file_polkit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_polkit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_polkit_proto_goTypes = []any{
	(PolkitResult)(0),                     // 0: bor.policy.v1.PolkitResult
	(*PolkitPolicy)(nil),                  // 1: bor.policy.v1.PolkitPolicy
	(*PolkitRule)(nil),                    // 2: bor.policy.v1.PolkitRule
	(*PolkitSubjectFilter)(nil),           // 3: bor.policy.v1.PolkitSubjectFilter
	(*PolkitActionDescription)(nil),       // 4: bor.policy.v1.PolkitActionDescription
	(*ReportPolkitCatalogueRequest)(nil),  // 5: bor.policy.v1.ReportPolkitCatalogueRequest
	(*ReportPolkitCatalogueResponse)(nil), // 6: bor.policy.v1.ReportPolkitCatalogueResponse
}
var file_polkit_proto_depIdxs = []int32{
	2, // 0: bor.policy.v1.PolkitPolicy.rules:type_name -> bor.policy.v1.PolkitRule
	3, // 1: bor.policy.v1.PolkitRule.subject:type_name -> bor.policy.v1.PolkitSubjectFilter
	0, // 2: bor.policy.v1.PolkitRule.result:type_name -> bor.policy.v1.PolkitResult
	4, // 3: bor.policy.v1.ReportPolkitCatalogueRequest.actions:type_name -> bor.policy.v1.PolkitActionDescription
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_polkit_proto_init() }
func file_polkit_proto_init() {
	if File_polkit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_polkit_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polkit_proto_goTypes,
		DependencyIndexes: file_polkit_proto_depIdxs,
		EnumInfos:         file_polkit_proto_enumTypes,
		MessageInfos:      file_polkit_proto_msgTypes,
	}.Build()
	File_polkit_proto = out.File
	file_polkit_proto_rawDesc = nil
	file_polkit_proto_goTypes = nil
	file_polkit_proto_depIdxs = nil
}
