// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Vute Tech LTD
// Copyright (C) 2026 Bor contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v7.35.1
// source: session_access.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionEndAction is what happens to a running session when its allowed
// window ends.
type SessionEndAction int32

const (
	// Treated as SESSION_END_ACTION_LOCK.
	SessionEndAction_SESSION_END_ACTION_UNSPECIFIED SessionEndAction = 0
	// Lock the screen; the session and its applications keep running.
	SessionEndAction_SESSION_END_ACTION_LOCK SessionEndAction = 1
	// Terminate the session (log the user off).
	SessionEndAction_SESSION_END_ACTION_LOGOUT SessionEndAction = 2
)

// Enum value maps for SessionEndAction.
var (
	SessionEndAction_name = map[int32]string{
		0: "SESSION_END_ACTION_UNSPECIFIED",
		1: "SESSION_END_ACTION_LOCK",
		2: "SESSION_END_ACTION_LOGOUT",
	}
	SessionEndAction_value = map[string]int32{
		"SESSION_END_ACTION_UNSPECIFIED": 0,
		"SESSION_END_ACTION_LOCK":        1,
		"SESSION_END_ACTION_LOGOUT":      2,
	}
)

func (x SessionEndAction) Enum() *SessionEndAction {
	p := new(SessionEndAction)
	*p = x
	return p
}

func (x SessionEndAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionEndAction) Descriptor() protoreflect.EnumDescriptor {
	return file_session_access_proto_enumTypes[0].Descriptor()
}

func (SessionEndAction) Type() protoreflect.EnumType {
	return &file_session_access_proto_enumTypes[0]
}

func (x SessionEndAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionEndAction.Descriptor instead.
func (SessionEndAction) EnumDescriptor() ([]byte, []int) {
	return file_session_access_proto_rawDescGZIP(), []int{0}
}

// SessionAccessPolicy controls when selected users or groups may use a
// desktop session. The agent enforces it in two layers: logind actions
// (lock/terminate at the window boundary, warning notifications, re-lock
// watchdog) and optionally pam_time (denies unlocking and new logins
// outside the allowed windows).
//
// A user's allowed time is the union of the windows of every rule that
// targets them, across all bound SessionAccessPolicies. Users not targeted
// by any rule are unrestricted. Times are node-local wall clock.
type SessionAccessPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Rules []*SessionAccessRule   `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	// Layer 2 (pam_time) on/off. When unset, defaults to true.
	EnforcePam *bool `protobuf:"varint,2,opt,name=enforce_pam,json=enforcePam,proto3,oneof" json:"enforce_pam,omitempty"`
	// Also add sshd to the pam_time service list, denying SSH logins outside
	// the allowed windows. Default off: this is a desktop-usage feature and
	// an SSH lockout surprises admins.
	IncludeSsh    bool `protobuf:"varint,3,opt,name=include_ssh,json=includeSsh,proto3" json:"include_ssh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAccessPolicy) Reset() {
	*x = SessionAccessPolicy{}
	mi := &file_session_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAccessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAccessPolicy) ProtoMessage() {}

func (x *SessionAccessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_session_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAccessPolicy.ProtoReflect.Descriptor instead.
func (*SessionAccessPolicy) Descriptor() ([]byte, []int) {
	return file_session_access_proto_rawDescGZIP(), []int{0}
}

func (x *SessionAccessPolicy) GetRules() []*SessionAccessRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *SessionAccessPolicy) GetEnforcePam() bool {
	if x != nil && x.EnforcePam != nil {
		return *x.EnforcePam
	}
	return false
}

func (x *SessionAccessPolicy) GetIncludeSsh() bool {
	if x != nil {
		return x.IncludeSsh
	}
	return false
}

// SessionAccessRule grants a set of users/groups a weekly schedule of
// allowed periods.
type SessionAccessRule struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Target users and/or groups; at least one of the two lists must be
	// non-empty. Group targets are expanded to user lists on the node at
	// apply time. "root" is never restricted.
	Users  []string `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Groups []string `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	// Allowed periods, node-local time. Within one rule and day, windows
	// must not overlap (they may touch).
	Windows   []*SessionAccessWindow `protobuf:"bytes,4,rep,name=windows,proto3" json:"windows,omitempty"`
	EndAction SessionEndAction       `protobuf:"varint,5,opt,name=end_action,json=endAction,proto3,enum=bor.policy.v1.SessionEndAction" json:"end_action,omitempty"`
	// Minutes before the window end at which to warn the logged-in user.
	// Strictly descending. Empty means the default [30, 15, 5].
	WarnMinutes   []int32 `protobuf:"varint,6,rep,packed,name=warn_minutes,json=warnMinutes,proto3" json:"warn_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAccessRule) Reset() {
	*x = SessionAccessRule{}
	mi := &file_session_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAccessRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAccessRule) ProtoMessage() {}

func (x *SessionAccessRule) ProtoReflect() protoreflect.Message {
	mi := &file_session_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAccessRule.ProtoReflect.Descriptor instead.
func (*SessionAccessRule) Descriptor() ([]byte, []int) {
	return file_session_access_proto_rawDescGZIP(), []int{1}
}

func (x *SessionAccessRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SessionAccessRule) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SessionAccessRule) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *SessionAccessRule) GetWindows() []*SessionAccessWindow {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *SessionAccessRule) GetEndAction() SessionEndAction {
	if x != nil {
		return x.EndAction
	}
	return SessionEndAction_SESSION_END_ACTION_UNSPECIFIED
}

func (x *SessionAccessRule) GetWarnMinutes() []int32 {
	if x != nil {
		return x.WarnMinutes
	}
	return nil
}

// SessionAccessWindow is a weekly-recurring allowed period.
type SessionAccessWindow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Days the window starts on: "mon".."sun".
	Days []string `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	// Start of the allowed period, "HH:MM" (24h).
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// End of the allowed period, "HH:MM" (24h). An end at or before the
	// start crosses midnight into the next day ("22:00"-"02:00").
	End           string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAccessWindow) Reset() {
	*x = SessionAccessWindow{}
	mi := &file_session_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAccessWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAccessWindow) ProtoMessage() {}

func (x *SessionAccessWindow) ProtoReflect() protoreflect.Message {
	mi := &file_session_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAccessWindow.ProtoReflect.Descriptor instead.
func (*SessionAccessWindow) Descriptor() ([]byte, []int) {
	return file_session_access_proto_rawDescGZIP(), []int{2}
}

func (x *SessionAccessWindow) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *SessionAccessWindow) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *SessionAccessWindow) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

var File_session_access_proto protoreflect.FileDescriptor

var file_session_access_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0xa4, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x36, 0x0a,
	0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62,
	0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05,
	0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x5f, 0x70, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x6e,
	0x66, 0x6f, 0x72, 0x63, 0x65, 0x50, 0x61, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x0b, 0x69,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x73, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x53, 0x73, 0x68, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x6d, 0x22, 0x84, 0x02, 0x0a,
	0x11, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x12, 0x3c, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73,
	0x12, 0x3e, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x21, 0x0a, 0x0c, 0x77, 0x61, 0x72, 0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x77, 0x61, 0x72, 0x6e, 0x4d, 0x69, 0x6e, 0x75,
	0x74, 0x65, 0x73, 0x22, 0x51, 0x0a, 0x13, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x79, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x2a, 0x72, 0x0a, 0x10, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x45, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x1e, 0x53, 0x45,
	0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b,
	0x0a, 0x17, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x53,
	0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x4c, 0x4f, 0x47, 0x4f, 0x55, 0x54, 0x10, 0x02, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x75, 0x74, 0x65, 0x54, 0x65, 0x63,
	0x68, 0x2f, 0x42, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3b, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_session_access_proto_rawDescOnce sync.Once
	file_session_access_proto_rawDescData = file_session_access_proto_rawDesc
)

func file_session_access_proto_rawDescGZIP() []byte {
	file_session_access_proto_rawDescOnce.Do(func() {
		file_session_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_session_access_proto_rawDescData)
	})
	return file_session_access_proto_rawDescData
}

var file_session_access_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_session_access_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_session_access_proto_goTypes = []any{
	(SessionEndAction)(0),       // 0: bor.policy.v1.SessionEndAction
	(*SessionAccessPolicy)(nil), // 1: bor.policy.v1.SessionAccessPolicy
	(*SessionAccessRule)(nil),   // 2: bor.policy.v1.SessionAccessRule
	(*SessionAccessWindow)(nil), // 3: bor.policy.v1.SessionAccessWindow
}
var file_session_access_proto_depIdxs = []int32{
	2, // 0: bor.policy.v1.SessionAccessPolicy.rules:type_name -> bor.policy.v1.SessionAccessRule
	3, // 1: bor.policy.v1.SessionAccessRule.windows:type_name -> bor.policy.v1.SessionAccessWindow
	0, // 2: bor.policy.v1.SessionAccessRule.end_action:type_name -> bor.policy.v1.SessionEndAction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_session_access_proto_init() }
func file_session_access_proto_init() {
	if File_session_access_proto != nil {
		return
	}
	file_session_access_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_session_access_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_access_proto_goTypes,
		DependencyIndexes: file_session_access_proto_depIdxs,
		EnumInfos:         file_session_access_proto_enumTypes,
		MessageInfos:      file_session_access_proto_msgTypes,
	}.Build()
	File_session_access_proto = out.File
	file_session_access_proto_rawDesc = nil
	file_session_access_proto_goTypes = nil
	file_session_access_proto_depIdxs = nil
}
